export const userOrder = {
    ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',

    ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
    ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAIL: 'ORDER_DETAILS_FAIL',
    
    ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
    ORDER_PAY_FAIL: 'ORDER_PAY_FAIL',
    ORDER_PAY_RESET: 'ORDER_PAY_RESET',
    
    MY_ORDERS_LIST_REQUEST: 'MY_ORDERS_LIST_REQUEST',
    MY_ORDERS_LIST_SUCCESS: 'MY_ORDERS_LIST_SUCCESS',
    MY_ORDERS_LIST_FAIL: 'MY_ORDERS_LIST_FAIL',
    MY_ORDERS_LIST_RESET: 'MY_ORDERS_LIST_RESET',
}